export enum ACTION_TYPES {
    SET_INITIAL_CURRENCY_VALUE="SET_INITIAL_CURRENCY_VALUE",  
    SET_CURRENCY_ARRAY="SET_CURRENCY_ARRAY",   
    SET_SELECTED_CURRENCY="SET_SELECTED_CURRENCY",
    SET_FINAL_CURRENCY="SET_FINAL_CURRENCY",
    SET_LOADED_FALSE="SET_LOADED_FALSE",
    SET_SELECTED_CURRENCIES_NIL="SET_SELECTED_CURRENCIES_NIL"
}
